<<<<<<< HEAD
version: '3.8'
services:
  db:
    container_name: db
    image: postgres:16
=======
services:
  db:
    container_name: db
    image: postgres:latest
>>>>>>> master
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
<<<<<<< HEAD

  redis:
    image: redis
    ports:
      - "6379:6379"
      
volumes:
  db-data:
=======
  
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
>>>>>>> master
